### ISSUE TITLE
Can't push to repo.

### ISSUE THREAD

**Issue by comcc2** [RIDGIDSoftwareSolutions/til#1]
I'm probably missing something obvious.

Js-MacBook-Pro:til comcc2$ git status 
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean
Js-MacBook-Pro:til comcc2$ git remote -v
origin  git@github.com:RIDGIDSoftwareSolutions/til.git (fetch)
origin  git@github.com:RIDGIDSoftwareSolutions/til.git (push)
Js-MacBook-Pro:til comcc2$ git push
ERROR: Permission to RIDGIDSoftwareSolutions/til.git denied to comcc2.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by coridn** [comment]
The only collaborators was set to Owners.

I've added RSS Push and Pull as Collaborators so anyone can add to this.
